/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type NameVariable = {
  family?: string;
  given?: string;
  "dropping-particle"?: string;
  "non-dropping-particle"?: string;
  suffix?: string;
  "comma-suffix"?: string | number | boolean;
  "static-ordering"?: string | number | boolean;
  literal?: string;
  "parse-names"?: string | number | boolean;
};
export type DateVariable = {
  "date-parts"?:
    | [[string | number] | [string | number, string | number] | [string | number, string | number, string | number]]
    | [
        [string | number] | [string | number, string | number] | [string | number, string | number, string | number],
        [string | number] | [string | number, string | number] | [string | number, string | number, string | number]
      ];
  season?: string | number;
  circa?: string | number | boolean;
  literal?: string;
  raw?: string;
};
/**
 * JSON schema for CSL input data
 */
export type CslData = {
  type:
    | "article"
    | "article-journal"
    | "article-magazine"
    | "article-newspaper"
    | "bill"
    | "book"
    | "broadcast"
    | "chapter"
    | "classic"
    | "collection"
    | "dataset"
    | "document"
    | "entry"
    | "entry-dictionary"
    | "entry-encyclopedia"
    | "figure"
    | "graphic"
    | "hearing"
    | "interview"
    | "legal_case"
    | "legislation"
    | "manuscript"
    | "map"
    | "motion_picture"
    | "musical_score"
    | "pamphlet"
    | "paper-conference"
    | "patent"
    | "performance"
    | "periodical"
    | "personal_communication"
    | "post"
    | "post-weblog"
    | "regulation"
    | "report"
    | "review"
    | "review-book"
    | "software"
    | "song"
    | "speech"
    | "standard"
    | "thesis"
    | "treaty"
    | "webpage";
  id: string | number;
  categories?: string[];
  language?: string;
  journalAbbreviation?: string;
  shortTitle?: string;
  author?: NameVariable[];
  "collection-editor"?: NameVariable[];
  composer?: NameVariable[];
  "container-author"?: NameVariable[];
  director?: NameVariable[];
  editor?: NameVariable[];
  "editorial-director"?: NameVariable[];
  interviewer?: NameVariable[];
  illustrator?: NameVariable[];
  "original-author"?: NameVariable[];
  recipient?: NameVariable[];
  "reviewed-author"?: NameVariable[];
  translator?: NameVariable[];
  accessed?: DateVariable;
  container?: DateVariable;
  "event-date"?: DateVariable;
  issued?: DateVariable;
  "original-date"?: DateVariable;
  submitted?: DateVariable;
  abstract?: string;
  annote?: string;
  archive?: string;
  archive_location?: string;
  "archive-place"?: string;
  authority?: string;
  "call-number"?: string;
  "chapter-number"?: string;
  "citation-number"?: string;
  "citation-label"?: string;
  "collection-number"?: string;
  "collection-title"?: string;
  "container-title"?: string;
  "container-title-short"?: string;
  dimensions?: string;
  DOI?: string;
  edition?: string | number;
  event?: string;
  "event-place"?: string;
  "first-reference-note-number"?: string;
  genre?: string;
  ISBN?: string;
  ISSN?: string;
  issue?: string | number;
  jurisdiction?: string;
  keyword?: string;
  locator?: string;
  medium?: string;
  note?: string;
  number?: string | number;
  "number-of-pages"?: string;
  "number-of-volumes"?: string | number;
  "original-publisher"?: string;
  "original-publisher-place"?: string;
  "original-title"?: string;
  page?: string;
  "page-first"?: string;
  PMCID?: string;
  PMID?: string;
  publisher?: string;
  "publisher-place"?: string;
  references?: string;
  "reviewed-title"?: string;
  scale?: string;
  section?: string;
  source?: string;
  status?: string;
  title?: string;
  "title-short"?: string;
  URL?: string;
  version?: string;
  volume?: string | number;
  "year-suffix"?: string;
}[];
